os: linux

language: python
branches:
  only:
    - master
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

install:
  - npm install
  - npm run build

script:
  - docker-compose run web sh -c "python projement/manage.py test api.tests"

notifications:
  email: false
