# Generated by Django 3.0.2 on 2020-01-08 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Project title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Project start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Project end date')),
                ('estimated_design', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Estimated design hours')),
                ('actual_design', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Actual design hours')),
                ('estimated_development', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Estimated development hours')),
                ('actual_development', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Actual development hours')),
                ('estimated_testing', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Estimated testing hours')),
                ('actual_testing', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Actual testing hours')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TagAddingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=240)),
                ('time_to_add', models.TimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tag'),
        ),
        migrations.CreateModel(
            name='InitialDataOfProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_actual_design', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('initial_actual_development', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('initial_actual_testing', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_delta_actual_design', models.CharField(blank=True, max_length=164)),
                ('resulting_actual_design', models.CharField(blank=True, max_length=164)),
                ('change_delta_actual_development', models.CharField(blank=True, max_length=164)),
                ('resulting_actual_development', models.CharField(blank=True, max_length=164)),
                ('change_delta_actual_testing', models.CharField(blank=True, max_length=164)),
                ('resulting_actual_testing', models.CharField(blank=True, max_length=164)),
                ('change_time', models.TimeField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
    ]
