# Generated by Django 3.0.2 on 2020-01-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200113_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='changed_by',
        ),
    ]
